apiVersion: v1
kind: Service
metadata:
  name: my-rtdb-service
  namespace: oge
  labels:
    app: behind-rtdb
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: rtdb-vzdb-port
      protocol: TCP
      name: rtdb-vzdb-port
      nodePort: {{ .Values.service.port }}
  selector:
    app.kubernetes.io/name: {{ include "rtdb-vzdb.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
